# Generated by Django 4.2.7 on 2024-03-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao', models.CharField(max_length=50)),
                ('tipo_certificado', models.CharField(max_length=100)),
                ('custo_de_vida', models.IntegerField(default=0)),
                ('avaliacao_final', models.IntegerField(default=0)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chfrontend.instituicao')),
            ],
        ),
    ]
