# Generated by Django 4.2.7 on 2024-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chfrontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.CharField(default='', max_length=50),
        ),
    ]
