# Generated by Django 4.2.7 on 2024-03-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chfrontend', '0002_curso_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='instituicao',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Instituicao',
        ),
    ]
