# Generated by Django 4.2.7 on 2024-03-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chfrontend', '0003_alter_curso_instituicao_delete_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='avaliacao_final',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='custo_de_vida',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Médio', 'Médio'), ('Baixo', 'Baixo')], max_length=5),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao',
            field=models.CharField(choices=[('1', '1 ano'), ('2', '2 anos'), ('3', '3 anos'), ('4', '4 anos'), ('5', '5 anos')], max_length=1),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo_certificado',
            field=models.CharField(choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('PhD', 'PhD')], max_length=3),
        ),
    ]
