# Generated by Django 4.2.7 on 2024-03-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chfrontend', '0004_alter_curso_avaliacao_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo_certificado',
            field=models.CharField(choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('PhD', 'PhD')], max_length=5),
        ),
    ]
