# Generated by Django 4.2.7 on 2024-03-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chfrontend', '0005_alter_curso_tipo_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='custo_de_vida',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Médio', 'Médio'), ('Baixo', 'Baixo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='instituicao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo_certificado',
            field=models.CharField(choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('PhD', 'PhD')], max_length=10),
        ),
    ]
